name: 'Extract PR data'
description: 'Extracting PR data and emitting some useful values to output'
inputs:
  gh_token:
    description: 'Access token'
    required: true
  pr_number: 
    description: 'Number of pull request to access'
    required: true
  repository: 
    description: '`github.repository` of `github` context'
    required: true
outputs:
  env_url: # id of output
    description: 'Env url'
runs:
  using: 'node16'
  main: 'dist/index.mjs'